Fixing some bugs

diff --git a/docker/cook b/docker/cook
--- a/docker/cook
+++ b/docker/cook
@@ -11,6 +11,11 @@ done
 SOURCE=${BASH_SOURCE[0]}
 local_dir="$( dirname $SOURCE)"
 
+if [ -z "$app_name" ]; then
+  echo -n "Missing application name : set it with -a option"
+  exit 1
+fi
+
 sudo docker rm cook-maker
 sudo docker build -t cook-maker $local_dir #--no-cache
-sudo docker run -it -v $(pwd):/build -e name=paf --name cook-maker cook-maker
+sudo docker run -it -v $(pwd):/build -e name=$app_name --name cook-maker-$app_name cook-maker
